#pragma once

#define SCE_GCODE_DEFAULT 0
#define SCE_GCODE_COMMENT 1
#define SCE_GCODE_COMMENT_ML 2
#define SCE_GCODE_G 3
#define SCE_GCODE_M 4
#define SCE_GCODE_PARAM 5
#define SCE_GCODE_VAR 6 
#define SCE_GCODE_NUMBER 7 
#define SCE_GCODE_COORDINATE 8
#define SCE_GCODE_WORD 9 
#define SCE_GCODE_OPERATORS  10
#define SCE_GCODE_IDENTIFIER 11
#define SCE_GCMC_DEFAULT 12
#define SCE_GCMC_WORD1 13 
#define SCE_GCMC_WORD2 14
#define SCE_GCMC_STRING 15

#define SCLEX_GCODE 200
#define SCLEX_GCMC 201

