#pragma once
//#include "wx/wx.h"
extern const char *gcode_gettext(const char *s);
#define _(String) gcode_gettext((String))

#define YA_WRONG_N _("Wrong N value")
#define YA_WRONG_LETTER _("Wrong letter: %c")
#define YA_CONFLICT_MMODAL_GROUP _("Conflict M%d modal group")
#define YA_CAN_NOT_CALLED_HERE _("CmdParser::read_set_parameter can not called here")
#define YA_NAMED_PARAMETER_NOT_SUPPORTED _("Named parameter does not support yet")
#define YA_MUILTISPINDLE_NOT_SUPPORTED _("Letter $ - multishpindle not supported")
#define YA_SUBNAME_NOT_SUPPORTED _("Subritine name does not supported")
#define YA_MULTIPLE_WORDS_ON_ONE_LINE  _("Multiply word %c is defened")
#define YA_CALC_RESULT_NOT_NUMBER _("Calculation resulted is 'not a number'")
#define YA_CALC_RESULT_INFINITY _("Calculation resulted is 'infinity'")
#define YA_BAD_NUMBER_FORMAT1 _("Bad number format parsing '%s'")
#define YA_CUTER_COMP_INVALID_ARC _("Cutter compensation has generated an invalid arc with mismatched radiuses r1 %f r2 %f")
#define YA_CUTER_COMP_ARC_MOVE _("Arc move in concave corner cannot be reached by the tool without gouging")
#define YA_CUTER_COMP_UNSUPPORTED_PLANE _("Unsupported plane in cutter compensation")
#define YA_CUTER_COMP_STRAIGHT_TRAVERSE _("Straight traverse in concave corner cannot be reached by the tool without gouging")
#define YA_CUTER_COMP_STRAIGHT_FEED _("Straight feed in concave corner cannot be reached by the tool without gouging")
#define YA_CYCLES_WITH_CUT_COMP_ON _("Cannot use canned cycles with cutter compensation on")
#define YA_G85_G88_NOTSUPPORTED _("[G85;G88] not supported yet")
#define YA_G74_G84_NOTSUPPORTED _("G74 & G84 not supported yet")
#define YA_FILE_NAME_NOTSPECIFYED _("File name not specified")
#define YA_CANNOT_OPEN_FILE _("Can not open file %s")
#define YA_CANNOT_SEEK_IN_FILE _("Can not seek to position %ld of file")
#define YA_CANNOT_FIND_SUBRATINE _("Can not find subroutinue: %s")
#define YA_P_WORD_MISSING_WITH_M98 _("P word missing with M98")
#define YA_G93_NOT_SUPPORTED _("G93 Inverse Time Mode not supported")
#define YA_G95_NOT_SUPPORTED _("G95 - is Units per Revolution Mode not supported")
#define YA_INCORRECT_FEED_VALUE _("Incorrect feed value")
#define YA_TOO_MANY_PARAM_G4 _("Too many parameters for dwell G4")
#define YA_D_MUST_BE_SPECIFY_G96 _("Word 'D' must be defined for G96 (CSS mode)")
#define YA_S_MUST_BE_SPECIFY_G96 _("Word 'S' must be defined for G96 (CSS mode)")
#define YA_P_MUST_BE_SPECIFY_G10 _("Word 'P' must be defined for G10")
#define YA_L_MUST_BE_SPECIFY_G10 _("Word 'L' must be defined for G10")
#define YA_L_MUST_BE_2_G10 "Can work only with L2 for G10 "
#define YA_P_IS_OUT_OF_RANGE _("Word 'P' is out of range")
#define YA_H_MUST_BE_SPECIFY_G43G44 _("Word 'H' must be defined for G43 and G44")
#define YA_SPINDLE_SPEED_IS_INCORRECT _("Spindle speed  is incorrect")
#define YA_INVALID_TOOL_ID_USED _("Invalid tool id used")
#define YA_TOOL_ID_NOTSPECIFYED_M6 ("Tool id is not spesified in M6")
#define YA_G7G8_NOT_SUPPORTED _("G7 and G8 does not support yet")
#define YA_G921_G922_NOT_SUPPORTED _("G92.1 and G92.2 not implemented yet")
#define YA_CANNOT_CHANGE_AXIS_COORDSYS_WITH_CUTTER_RADIUS_COMP _("Cannot change coordinate systems with cutter radius compensation on")
#define YA_G41_1_G42_1_WITH_NO_D _("G%d.1 with no D word")
#define YA_G41_1_G42_1_WITH_L_BUT_PLANE_NOT_G18 _("G%d.1 with L word, but plane is not G18")
#define YA_NAMED_PARAMETERS_NOT_SUPPORTED _("Named parameter does not support yet")
#define YA_UNKNOWN_WORD _("Unknown word starting with %c")
#define YA_EXPECTED_RESH _("Expected # reading parameter")
#define YA_EXPECTED_RIGHT_BRCKET _("Expected ] reading bracketed parameter")
#define YA_UNKNOWN_OPERATION_NAME_STARTING_WITH _("Unknown operation name starting with %c")
#define YA_CANNOT_FEED_WITH_ZERO_SPINDLE _("Cannot feed with zero spindle speed in feed per rev mode")
#define YA_INVALID_PLANE_FOR_CUT_COMP _("Invalid plane for cutter compensation")
#define YA_G33_NOT_SUPPORTED _("G33 not supported")
#define YA_G76_NOT_SUPPORTED _("G76 not supported")
#define YA_LENGHT_CUT_COMP_NOT_GREATER_TOOL_RADIUS _("Length of cutter compensation entry move is not greater than the tool radius")
#define YA_ZERO_DEGREE_INSIDE_CORNER_IS_INVALID _("Zero degree inside corner is invalid for cutter compensation")
#define YA_ARC_STRAIGHT_MAKE_BAD_CORNER _("Arc to straight motion makes a corner the compensated tool can't fit in without gouging")
#define YA_UNKNOWN_OPERATION _("Unknown operation")
#define YA_UNKNOWN_WORD_WHERE_UNARY_OPERATION_COULD_BE _("Unknown word where unary operation could be")
#define YA_X_AND_Y_WORDS_MISSING_FOR_ARC_IN_XY_PLANE _("X and y words missing for arc in xy plane")
#define YA_X_AND_Z_WORDS_MISSING_FOR_ARC_IN_XZ_PLANE _("X and z words missing for arc in xz plane")
#define YA_Y_AND_Z_WORDS_MISSING_FOR_ARC_IN_YZ_PLANE _("Y and z words missing for arc in yz plane")
#define YA_X_VALUE_UNSPECIFIED_IN_YZ_PLANE_CANNED_CYCLE _("X value unspecified in yz plane canned cycle")
#define YA_Q_WORD_MISSING_WITH_G73 _("Q word missing with g73")
#define YA_Y_VALUE_UNSPECIFIED_IN_XZ_PLANE_CANNED_CYCLE _("Y value unspecified in xz plane canned cycle")
#define YA_Z_VALUE_UNSPECIFIED_IN_XY_PLANE_CANNED_CYCLE _("Z value unspecified in xy plane canned cycle")
#define YA_ZERO_OR_NEGATIVE_ARGUMENT_TO_LN _("Zero or negative argument to ln")
#define YA_RADIUS_COMP_ONLY_IN_XY_OR_XZ _("Cutter radius compensation allowed only in XY, XZ planes")
#define YA_ALL_AXES_MISSING_WITH_G52_OR_G92  _("All axes missing with g52 or g92")
#define YA_ALL_AXES_MISSING_WITH_MOTION_CODE _("All axes missing with motion code")
#define YA_ARC_RADIUS_TOO_SMALL_TO_REACH_END_POINT _("Arc radius too small to reach end point")
#define YA_ARGUMENT_TO_ACOS_OUT_OF_RANGE _("Argument to acos out of range")
#define YA_ARGUMENT_TO_ASIN_OUT_OF_RANGE _("Argument to asin out of range")
#define YA_ATTEMPT_TO_DIVIDE_BY_ZERO _("Attempt to divide by zero")
#define YA_ATTEMPT_TO_RAISE_NEGATIVE_TO_NON_INTEGER_POWER _("Attempt to raise negative to non integer power")
#define YA_BAD_FORMAT_INTEGER _("Bad format integer")
#define YA_BUG_CODE_NOT_G0_OR_G1 _("Bug code not g0 or g1")
#define YA_BUG_CODE_NOT_G2_OR_G3 _("Bug code not g2 or g3")
#define YA_BUG_IN_TOOL_RADIUS_COMP _("Bug in tool radius comp")
#define YA_BUG_PLANE_NOT_XY_YZ_OR_XZ _("Bug plane not xy yz or xz")
#define YA_SIDE_NOT_RIGHT_OR_LEFT _("Compensation type not left and no right")
#define YA_CANNOT_FEED_WITH_ZERO_FEED_RATE _("Cannot feed with zero feed rate")
#define YA_CANNOT_DO_ZERO_REPEATS_OF_CYCLE _("Cannot do zero repeats of cycle")
#define YA_BUG_UNKNOWN_OPERATION _("Bug unknown operation")
#define YA_CANNOT_CHANGE_AXIS_OFFSETS_WITH_CUTTER_RADIUS_COMP _("Cannot change axis offsets with cutter radius comp")
#define YA_CANNOT_TURN_CUTTER_RADIUS_COMP_ON_WHEN_ON _("Cannot turn cutter radius comp on when on")
#define YA_CANNOT_USE_AXIS_VALUES_WITH_G80 _("Cannot use axis values with g80")
#define YA_CANNOT_USE_AXIS_VALUES_WITHOUT_A_G_CODE_THAT_USES_THEM _("Cannot use axis values without a g code that uses them")
#define YA_CANNOT_USE_G53_WITH_CUTTER_RADIUS_COMP _("Cannot use g53 with cutter radius comp")
#define YA_CANNOT_USE_TWO_G_CODES_THAT_BOTH_USE_AXIS_VALUES _("Cannot use two g codes that both use axis values")
#define YA_COMMAND_TOO_LONG _("Command too long")
#define YA_CURRENT_POINT_SAME_AS_END_POINT_OF_ARC _("Current point same as end point of arc")
#define YA_DWELL_TIME_P_WORD_MISSING_WITH_G82 _("Dwell time p word missing with g82")
#define YA_EQUAL_SIGN_MISSING_IN_PARAMETER_SETTING _("Equal sign missing in parameter setting")
#define YA_G_CODE_OUT_OF_RANGE _("G code out of range")
#define YA_SOMEWORD_GIVEN_FOR_ARC_IN_THE_PLANE _("%c word given for arc in %s plane")
#define YA_SOMEWORDS_MISSING_IN_ABS_CENTERARC _("%c word missing in absolute center arc")
#define YA_ZERO_RADIUS_ARC_WITHARGS _("Zero-radius arc: start=(%c%.4f,%c%.4f) center=(%c%.4f,%c%.4f) end=(%c%.4f,%c%.4f) r1=%.4f r2=%.4f")
#define YA_RADIUS_TO_STARTARC_DIF_RADIUS_FROM_END _("Radius to end of arc differs from radius to start: start=(%c%.4f,%c%.4f) center=(%c%.4f,%c%.4f) end=(%c%.4f,%c%.4f) r1=%.4f r2=%.4f abs_err=%.4g rel_err=%.4f%%")
#define YA_RADIUS_OF_COMPENSTION_IS_NOT_GRATE_TOOL_RADIUS _("Radius of cutter compensation entry arc is not greater than the tool radius")
#define YA_ARC_MOVE_IN_CORNER_CANATBEREACH _("Arc move in concave corner cannot be reached by the tool without gouging")
#define YA_ARC_TO_ARC_INVALID_ARC_HAVE_SME_CENTERS _("Arc to arc motion is invalid because the arcs have the same center")
#define YA_ARC_TO_ARC_MAKE_CORNER_OFCOMP _("Arc to arc motion makes a corner the compensated tool can't fit in without gouging")
#define YA_LEFT_BRACKET_MISSING_AFTER_SLASH_WITH_ATAN _("Left bracket missing after slash with atan")
#define YA_LEFT_BRACKET_MISSING_AFTER_UNARY_OPERATION_NAME _("Left bracket missing after unary operation name")
#define YA_M_CODE_GREATER_THAN_199 _("M code greater than 199: M%d")
#define YA_MIXED_RADIUS_IJK_FORMAT_FOR_ARC _("Mixed radius ijk format for arc")
#define YA_NEGATIVE_D_WORD_TOOL_RADIUS_INDEX_USED _("Negative d word tool radius index used")
#define YA_NEGATIVE_G_CODE_USED _("Negative g code used")
#define YA_NEGATIVE_M_CODE_USED _("Negative m code used")
#define YA_NEGATIVE_OR_ZERO_Q_VALUE_USED _("Negative or zero q value used")
#define YA_NO_CHARACTERS_FOUND_IN_READING_REAL_VALUE _("No characters found in reading real value")
#define YA_NON_INTEGER_VALUE_FOR_INTEGER _("Non integer value for integer")
#define YA_R_I_J_K_WORDS_ALL_MISSING_FOR_ARC _("R i j k words all missing for arc")
#define YA_R_LESS_THAN_X_IN_CYCLE_IN_YZ_PLANE _("R less than x in cycle in yz plane")
#define YA_R_LESS_THAN_Y_IN_CYCLE_IN_XZ_PLANE _("R less than y in cycle in xz plane")
#define YA_R_LESS_THAN_Z_IN_CYCLE_IN_XY_PLANE _("R less than z in cycle in xy plane")
#define YA_SLASH_MISSING_AFTER_FIRST_ATAN_ARGUMENT _("Slash missing after first atan argument")
#define YA_PARAMETER_NUMBER_OUT_OF_RANGE _("Parameter number out of range")
#define YA_PARAMETER_NUMBER_READONLY _("Parameter is readonly")
#define YA_Q_WORD_MISSING_WITH_G83 _("Q word missing with g83")
#define YA_TOOL_RADIUS_NOT_LESS_THAN_ARC_RADIUS_WITH_COMP _("Tool radius not less than arc radius with comp")
#define YA_TWO_G_CODES_USED_FROM_SAME_MODAL_GROUP _("Two g codes used from same modal group: G%d")
#define YA_UNCLOSED_EXPRESSION _("Unclosed expression")
#define YA_UNKNOWN_G_CODE_USED _("Unknown g code used: G%d")


/*
#define NCE_BAD_NUMBER_FORMAT _("Bad number format")
#define NCE_BUG_BAD_G_CODE_MODAL_GROUP_0 _("Bug bad g code modal group 0")
#define NCE_BUG_CODE_NOT_G17_G18_OR_G19 _("Bug code not g17 g18 or g19")
#define NCE_BUG_CODE_NOT_G20_OR_G21 _("Bug code not g20 or g21")
#define NCE_BUG_CODE_NOT_G28_OR_G30 _("Bug code not g28 or g30")
#define NCE_BUG_CODE_NOT_G4_G10_G28_G30_G52_G53_OR_G92_SERIES _("Bug code not g4 g10 g28 g30 g52 g53 or g92 series")
#define NCE_BUG_CODE_NOT_G61_G61_1_OR_G64 _("Bug code not g61 g61.1 or g64")
#define NCE_BUG_CODE_NOT_G90_OR_G91 _("Bug code not g90 or g91")
#define NCE_BUG_CODE_NOT_G98_OR_G99 _("Bug code not g98 or g99")
#define NCE_BUG_CODE_NOT_IN_G52_G92_SERIES _("Bug code not in g52 or g92 series")
#define NCE_BUG_CODE_NOT_IN_RANGE_G54_TO_G593 _("Bug code not in range g54 to g593")
#define NCE_BUG_CODE_NOT_M0_M1_M2_M30_M60_M99 _("Bug code not m0 m1 m2 m30 m60 m99")
#define NCE_BUG_DISTANCE_MODE_NOT_G90_OR_G91 _("Bug distance mode not g90 or g91")
#define NCE_BUG_FUNCTION_SHOULD_NOT_HAVE_BEEN_CALLED _("Bug function should not have been called")
#define NCE_BUG_UNKNOWN_MOTION_CODE _("Bug unknown motion code")
#define NCE_CANNOT_CREATE_BACKUP_FILE _("Cannot create backup file")
#define NCE_CANNOT_MAKE_ARC_WITH_ZERO_FEED_RATE _("Cannot make arc with zero feed rate")
#define NCE_CANNOT_OPEN_BACKUP_FILE _("Cannot open backup file")
#define NCE_CANNOT_OPEN_VARIABLE_FILE _("Cannot open variable file")
#define NCE_CANNOT_PROBE_WITH_CUTTER_RADIUS_COMP_ON _("Cannot probe with cutter radius comp on")
#define NCE_CANNOT_PROBE_WITH_ZERO_FEED_RATE _("Cannot probe with zero feed rate")
#define NCE_CANNOT_PUT_A_B_IN_CANNED_CYCLE _("Cannot put a b in canned cycle")
#define NCE_CANNOT_PUT_A_C_IN_CANNED_CYCLE _("Cannot put a c in canned cycle")
#define NCE_CANNOT_PUT_AN_A_IN_CANNED_CYCLE _("Cannot put an a in canned cycle")
#define NCE_CANNOT_USE_G28_OR_G30_WITH_CUTTER_RADIUS_COMP _("Cannot use g28 or g30 with cutter radius comp")
#define NCE_CANNOT_USE_G53_INCREMENTAL _("Cannot use g53 incremental")
#define NCE_DWELL_TIME_MISSING_WITH_G4 _("Dwell time missing with g4")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G86 _("Dwell time p word missing with g86")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G88 _("Dwell time p word missing with g88")
#define NCE_DWELL_TIME_P_WORD_MISSING_WITH_G89 _("Dwell time p word missing with g89")
#define NCE_F_WORD_MISSING_WITH_INVERSE_TIME_ARC_MOVE _("F word missing with inverse time arc move")
#define NCE_F_WORD_MISSING_WITH_INVERSE_TIME_G1_MOVE _("F word missing with inverse time g1 move")
#define NCE_FILE_ENDED_WITH_NO_PERCENT_SIGN _("File ended with no percent sign")
#define NCE_FILE_ENDED_WITH_NO_PERCENT_SIGN_OR_PROGRAM_END _("File ended with no percent sign or program end")
#define NCE_FILE_NAME_TOO_LONG _("File name too long")
#define NCE_I_WORD_MISSING_WITH_G87 _("I word missing with g87")
#define NCE_J_WORD_MISSING_WITH_G87 _("J word missing with g87")
#define NCE_K_WORD_MISSING_WITH_G87 _("K word missing with g87")
#define NCE_MULTIPLE_$_WORDS_ON_ONE_LINE _("Multiple spindle choice ($) words on one line")
#define NCE_MUST_USE_G0_OR_G1_WITH_G53 _("Must use g0 or g1 with g53")
#define NCE_NEGATIVE_ARGUMENT_TO_SQRT _("Negative argument to sqrt")
#define NCE_NEGATIVE_F_WORD_USED _("Negative f word used")
#define NCE_NEGATIVE_H_WORD_USED _("Negative h word used")
#define NCE_NEGATIVE_L_WORD_USED _("Negative l word used")
#define NCE_NEGATIVE_P_WORD_USED _("Negative p word used")
#define NCE_NEGATIVE_SPINDLE_SPEED_USED _("Negative spindle speed used")
#define NCE_NEGATIVE_TOOL_ID_USED _("Negative tool id used")
#define NCE_NESTED_COMMENT_FOUND _("Nested comment found")
#define NCE_NULL_MISSING_AFTER_NEWLINE _("Null missing after newline")
#define NCE_PARAMETER_FILE_OUT_OF_ORDER _("Parameter file out of order")
#define NCE_QUEUE_IS_NOT_EMPTY_AFTER_PROBING _("Queue is not empty after probing")
#define NCE_R_CLEARANCE_PLANE_UNSPECIFIED_IN_CYCLE _("R clearance plane unspecified in cycle")
#define NCE_R_WORD_WITH_NO_G_CODE_THAT_USES_IT _("R word with no g code that uses it")
#define NCE_SPINDLE_NOT_TURNING_CLOCKWISE_IN_G84 _("Spindle not turning clockwise in g84")
#define NCE_SPINDLE_NOT_TURNING_IN_G86 _("Spindle not turning in g86")
#define NCE_SPINDLE_NOT_TURNING_IN_G87 _("Spindle not turning in g87")
#define NCE_SPINDLE_NOT_TURNING_IN_G88 _("Spindle not turning in g88")
#define NCE_SSCANF_FAILED _("Sscanf failed")
#define NCE_START_POINT_TOO_CLOSE_TO_PROBE_POINT _("Start point too close to probe point")
#define NCE_TOO_MANY_M_CODES_ON_LINE _("Too many m codes on line")
#define NCE_POCKET_MAX_TOO_LARGE _("Pocket max too large")
#define NCE_TWO_M_CODES_USED_FROM_SAME_MODAL_GROUP _("Two m codes used from same modal group")
#define NCE_UNABLE_TO_OPEN_FILE _("Unable to open file <%s>")
#define NCE_UNCLOSED_COMMENT_FOUND _("Unclosed comment found")
#define NCE_UNKNOWN_M_CODE_USED _("Unknown m code used: M%d")
#define NCE_ZERO_RADIUS_ARC _("Zero radius arc")
#define NCE_K_WORD_MISSING_WITH_G33 _("K word missing with g33/g33.1")
#define NCE_F_WORD_USED_WITH_G33 _("F word used with a g33/g33.1")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_E _("Unknown operation name starting with e")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_N _("Unknown operation name starting with n")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_G _("Unknown operation name starting with g")
#define NCE_UNKNOWN_OPERATION_NAME_STARTING_WITH_L _("Unknown operation name starting with l")
#define NCE_TOO_MANY_SUBROUTINE_PARAMETERS _("Too many subroutine parameters")
#define NCE_TOO_MANY_SUBROUTINE_LEVELS _("Too many subroutine levels")
#define NCE_CALL_STACK_UNDERRUN  _("Bug: call stack underrun")
#define NCE_UNKNOWN_COMMAND_IN_O_LINE _("Unknown control command in o word")
#define NCE_TOO_MANY_OWORD_LABELS _("Too many oword labels")
#define NCE_UNKNOWN_OWORD_NUMBER _("Unknown oword number")
#define NCE_NESTED_SUBROUTINE_DEFN _("Nested subroutine definition")
#define NCE_NOT_IN_SUBROUTINE_DEFN _("Not in subroutine definition")
#define NCE_FILE_NOT_OPEN _("File not open")
#define NCE_CANNOT_REOPEN_FILE _("cannot reopen file %s - removed or renamed? (%s)")
#define NCE_TXX_MISSING_FOR_M6 _("Need tool prepared -Txx- for toolchange")
#define NCE_CANNOT_CHANGE_PLANES_WITH_CUTTER_RADIUS_COMP_ON _("Cannot change planes with cutter radius compensation on")
#define NCE_P_WORD_MISSING_WITH_G76 _("P word missing with G76")
#define NCE_I_J_OR_K_WORDS_MISSING_WITH_G76 _("I J or K words missing with G76")
#define NCE_CANNOT_MOVE_ROTARY_AXES_WITH_G76 _("Cannot move rotary axes with G76")
#define NCE_MULTIPLE_E_WORDS_ON_ONE_LINE _("Multiple e words on one line")
#define NCE_NAMED_PARAMETER_NOT_TERMINATED _("Named parameter not terminated")
#define NCE_OUT_OF_MEMORY _("Out of memory")
#define NCE_S_WORD_MISSING_WITH_G96 _("S word missing with G96")
#define NCE_QUEUE_IS_NOT_EMPTY_AFTER_INPUT _("Queue is not empty after external input")
#define NCE_ANALOG_INPUT_WITH_WAIT_NOT_IMMEDIATE _("Can't select analog input with wait type != immediate return")
#define NCE_ZERO_TIMEOUT_WITH_WAIT_NOT_IMMEDIATE _("Zero timeout with wait type != immediate return")
#define NCE_BOTH_DIGITAL_AND_ANALOG_INPUT_SELECTED _("Invalid to select both a digital and an analog input with M66")
#define NCE_INVALID_OR_MISSING_P_AND_E_WORDS_FOR_WAIT_INPUT _("Need to have either a valid P or a valid E word with M66")
#define NCE_DIGITAL_INPUT_INVALID_ON_M66 _("Digital input selected out of bounds")
#define NCE_ANALOG_INPUT_INVALID_ON_M66 _("Analog input selected out of bounds")
#define NCE_W_VALUE_UNSPECIFIED_IN_UV_PLANE_CANNED_CYCLE _("W value unspecified in UV plane canned cycle")
#define NCE_U_VALUE_UNSPECIFIED_IN_VW_PLANE_CANNED_CYCLE _("U value unspecified in VW plane canned cycle")
#define NCE_V_VALUE_UNSPECIFIED_IN_UW_PLANE_CANNED_CYCLE _("V value unspecified in UW plane canned cycle")
#define NCE_R_LESS_THAN_W_IN_CYCLE_IN_UV_PLANE _("R less than W in cycle in UV plane")
#define NCE_R_LESS_THAN_U_IN_CYCLE_IN_VW_PLANE _("R less than U in cycle in VW plane")
#define NCE_R_LESS_THAN_V_IN_CYCLE_IN_UW_PLANE _("R less than V in cycle in UW plane")
#define NCE_A_FILE_IS_ALREADY_OPEN _("A file is already open")

*/